[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.test]
verbosity = 2

[rpc_endpoints]
# Add your RPC endpoints here
# mainnet = "YOUR_MAINNET_RPC_URL"
# sepolia = "YOUR_SEPOLIA_RPC_URL"

[etherscan]
# Add your Etherscan API key for verification
# mainnet = { key = "YOUR_ETHERSCAN_API_KEY" }
# sepolia = { key = "YOUR_ETHERSCAN_API_KEY" }
